import './globals.css'
import type { Metadata } from 'next'
import { Inter, Rubik_Bubbles, Roboto } from 'next/font/google'
import NavBar from './NavBar'
import AuthProvider  from './auth/Provider'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300'],
})
const rubikBubbles = Rubik_Bubbles({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bubbles'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme='winter'>
      <AuthProvider>
        <body className={roboto.className}>
          <NavBar />
          <main className='p-5'>
              {children}
          </main>
        </body>
      </AuthProvider>
    </html>
  )
}
